### ISSUE TITLE
cardano-explorer-api stop without error messages

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-rest#88]
observed on mainnet.

Could be some sql requests that is failing. more investigation is needed.

**Comment by johnalotoski** [comment]
The cardano-explorer-api service is failing on mainnet intermittently – usually for a few to several hours or days at a time, followed by normal operation for hours or days, with no predictability.  When it is in a period of failing, the service fails every few seconds and is then automatically restarted by systemd only to fail again a few seconds later.  One possibility is that this failure is caused by specific queries that are not predictably or routinely issued by explorer clients.

This issue is associated with JIRA ticket: [ADP-411](https://jira.iohk.io/browse/ADP-411)

To aid in root-cause analysis, logs were collected for a 1 hr period while the service was failing and are available from the JIRA ticket.

Review of the OS config and postgres config (ex: with pgHero) does not indicate a problem at the OS or postgres configuration level.

If these logs don't help identify the problem, we can take a look at obtaining strace output next

**Comment by johnalotoski** [comment]
Bump.  An update has been posted to ADP with example queries causing this behavior.

**Comment by johnalotoski** [comment]
Root cause for this ended up being related to a deployment configuration issue with the rate limit and systemd nofile service limit and has now been addressed.  It was not caused by an app issue.
